@startuml
!pragma layout smetana

class StreamingService {
    - users : ArrayList<User>
    - mediaLibrary : ArrayList<Media>
    - currentUser : User
}

Interface Media {
    getTitle
      getYear
      getCategory
}

class Movie {
   -String title
      -int year
      -String Category
}

class Series {
   -String title
   -int year
   -String Category
}

class Season {
    - episodes : ArrayList<Episode>
     -String title
     -int year
     -String Category
}

class Episode {
    - title : String
    - duration : int
    - episodeNumber : int
    play
}

class User {
    - username : String
    - password : String
}


'Relationer'

StreamingService  -->  User
StreamingService  --> Media


Media <|-- Movie
Media <|-- Series

Series  -->  Season
Season  -->  Episode


@enduml
