@startuml
!pragma layout smetana

class StreamingService {
    - users : ArrayList<User>
    - mediaLibrary : ArrayList<Media>
    - currentUser : User
}

Interface Media {
    - String title
    - int year
    - String category
}

class Movie {
    play
}

class Series {
    play
}

class Season {
    - episodes : ArrayList<Episode>
}

class Episode {
    - title : String
    - duration : int
    - episodeNumber : int
    play
}

class User {
    - username : String
    - password : String
}


'Relationer'

StreamingService  -->  User
StreamingService  --> Media


Media <|-- Movie
Media <|-- Series

Series  -->  Season
Season  -->  Episode


@enduml
