@startuml
!pragma layout smetana

title Chill Streaming Service - Class Diagram

package util {
    class FileIO {
        +saveData(list: ArrayList<String>, path: String, header: String): void
        +readData(path: String): ArrayList<String>
        +readData(path: String, length: int): String[]
    }

    class TextUI {
        -sc: Scanner
        +promptChoice(options: ArrayList<String>, limit: int, msg: String): ArrayList<String>
        +displayList(list: ArrayList<String>, msg: String): void
        +displayMsg(msg: String): void
        +promptNumeric(msg: String): int
        +promptText(msg: String): String
        +promptBinary(msg: String): boolean
    }
}

interface Media

class Series
class Season
class Episode
class Movie

class User {
    -username: String
    -password: String
    +getUsername(): String
    +getPassword(): String
    +setUsername(username: String): void
    +setPassword(password: String): void
    +toString(): String
}

class StreamingService {
    -users: ArrayList<User>
    -mediaLibrary: ArrayList<Media>
    -ui: TextUI
    -io: FileIO
    -currentUser: User

    +startSession(): void
    +endSession(): void
    -createUser(): void
    -userLogin(): void
}

class Main {
    +main(): void
}

StreamingService --> User : has >
StreamingService --> Media : has >
StreamingService --> TextUI : >
StreamingService --> FileIO : >

Season --> Series : has >
Episode --> Season : has >
Movie --> Media : is
Series --|> Media : is

Main --> StreamingService :  >

@enduml
